#!/bin/bash
set -eu

function main() {
    local subcommand=$1

    local -r ROLES=(
        'cplusplus'
        'git'
        'gui-applications'
        'nkf'
        'python'
        'shellcheck'
        'xmllint'
        'zip'
    )

    for role in ${ROLES[@]}; do
        pushd src/playbooks/roles/${role} && molecule ${subcommand} && popd
    done
}

main "$@"
