---

- name: Increase inotify limit
  become: yes
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'

- name: Test swap size
  tags:
    - test
    - never
  block:
    - name: Determine max_user_watches
      ansible.builtin.command: bash -c "cat /proc/sys/fs/inotify/max_user_watches"
      register: result
      changed_when: False
    - name: Assert swap size
      ansible.builtin.assert:
        that:
          - result.stdout == "524288"
        fail_msg: "actual size is {{ result.stdout }}"
