---

- name: Check swap partition existence
  ansible.builtin.command: bash -c "cat /etc/fstab | grep '[^ ]* *[^ ]* *swap' | awk '{print $1}'"
  register: checked_result
  changed_when: false

- name: Remove swap partition entries if exist
  become: yes
  with_items: "{{ checked_result.stdout_lines }}"
  mount:
    path: "none"
    src: "{{ item }}"
    state: "absent"
  notify:
    - disable swap devices and files for current session

- name: Test swap size for current session
  tags:
    - test
    - never
  block:
    - name: Determine swap size
      ansible.builtin.command: bash -c "grep SwapTotal /proc/meminfo | awk '{print $2}'"
      register: result
      changed_when: False
    - name: Assert swap size
      assert:
        that:
          - result.stdout == "0"
        fail_msg: "actual size is {{ result.stdout }}"
