---

- name: Check whether already installed clang 14
  command: |-
    which clang-14
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: Install clang 14
  when: checked_result.rc == 1
  block:
    - name: Install requirements
      become: yes
      apt:
        name:
          - apt-transport-https
          - lsb-release
          - software-properties-common
          - wget
    - name: Create temporary working directory
      tempfile:
        state: directory
      register: tmpdir
    - name: Download clang automatic installation script
      get_url:
        url: https://apt.llvm.org/llvm.sh
        dest: "{{ tmpdir.path }}/llvm.sh"
    - name: Execute clang automatic installation script
      become: yes
      # noqa no-changed-when
      command: "bash {{ tmpdir.path }}/llvm.sh 14"
    - name: Remove temporary working directory
      file:
        path: "{{ tmpdir.path }}"
        state: absent

- name: Install packages
  become: yes
  apt:
    name:
      - clang-format-14
      - cmake
      - g++
      - gdb
      - ninja-build

- name: Correct clang-format version to 14
  become: yes
  alternatives:
    link: /usr/bin/clang-format
    name: clang-format
    path: /usr/bin/clang-format-14
