---
- name: Add apt key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    filename: docker
    state: present

- name: Install packages
  become: yes
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

- name: Add user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Download compose-switch
  become: yes
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose-switch/releases/download/v{{ compose_switch_version }}/docker-compose-linux-amd64"
    dest: /usr/local/bin/compose-switch
    mode: 0755

- name: Create alternatives for docker-compose command
  become: yes
  community.general.alternatives:
    name: docker-compose
    link: /usr/local/bin/docker-compose
    path: /usr/local/bin/compose-switch

- name: Test for every session
  tags:
    - test
    - never
  block:
    - name: Test command existence
      ansible.builtin.command: bash -c "type {{ item }}"
      register: result
      changed_when: False
      with_items:
        - docker
        - docker-compose

- name: Test after rebooting
  tags:
    - test2
    - never
  block:
    - name: Test docker command usability
      ansible.builtin.command: docker run --rm hello-world
      changed_when: False
    - name: Test docker compose usability
      block:
        - name: Create temporary working directory
          ansible.builtin.tempfile:
            state: directory
          register: tmpdir
        - name: Put docker-compose.yml
          ansible.builtin.copy:
            src: "docker-compose.yml"
            dest: "{{ tmpdir.path }}/docker-compose.yml"
            mode: '0664'
        - name: Assert docker compose command usability
          ansible.builtin.command: docker compose ps
          args:
            chdir: "{{ tmpdir.path }}"
          changed_when: False
