---

- name: install packages
  become: yes
  apt:
    name: docker.io

- name: add vagrant user to docker group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes

- name: download docker-compose v1
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_v1_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: create directory to put docker cli-plugin
  file:
    path: /home/vagrant/.docker/cli-plugins
    state: directory
    mode: "0755"

- name: download docker-compose v2
  become: yes
  get_url:
    # TODO' Use `uname -m` for cross platform suffixes (since v2.0.1)
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_v2_version }}/docker-compose-linux-x86_64"
    dest: /home/vagrant/.docker/cli-plugins/docker-compose
    mode: 0755
