---

- name: install packages
  become: yes
  ansible.builtin.apt:
    name: xfce4-terminal

- name: create directory to put config file
  ansible.builtin.file:
    path: /home/vagrant/.config/xfce4/terminal
    state: directory

- name: add config file
  become: yes
  ansible.builtin.copy:
    src: terminalrc
    dest: /home/vagrant/.config/xfce4/terminal
    mode: 0664

- name: remove CR code in config file
  become: yes
  replace:
    dest: /home/vagrant/.config/xfce4/terminal/terminalrc
    regexp: '\r'
    replace: ''
