---
- name: Determine user directory paths
  ansible.builtin.command: "xdg-user-dir {{ item }}"
  changed_when: False
  register: paths
  loop:
    - DESKTOP
    - DOWNLOAD
    - TEMPLATES
    - PUBLICSHARE
    - DOCUMENTS
    - MUSIC
    - PICTURES
    - VIDEOS

- name: Stat user directories
  ansible.builtin.stat:
    path: "{{ item }}"
  register: stats
  loop: "{{ paths.results | map(attribute='stdout') }}"

- name: Create well known English-named user directories
  ansible.builtin.command: |-
    bash -c "LC_ALL=C xdg-user-dirs-update"
  when: stats.results | map(attribute='stat.exists') is not all
  changed_when: True
