---

- name: Show plugin name to install
  ansible.builtin.debug:
    var: vscode_plugin

- name: Check whether already installed
  ansible.builtin.command: bash -c "code --list-extensions | grep -x '{{ vscode_plugin }}'"
  register: checked_result
  failed_when: checked_result.rc not in [0, 1]
  changed_when: False # No effect on environment

- name: Install plugin
  ansible.builtin.command: bash -c "code --install-extension '{{ vscode_plugin }}'"
  when: checked_result.rc == 1 # not installed yet
