"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
${username}@${hostname} ${time}\
$cmd_duration\
$python\
$jobs
in ${directory}\
$git_branch\
$git_commit\
$git_state\
$status
$character"""

[username]
format = '[$user]($style)'
show_always = true

[hostname]
format = '[$hostname]($style)'
ssh_only = false

[time]
disabled = false

[python]
symbol = 'python '

[jobs]
format = '[running ${number} job\(s\)]($style) '
number_threshold = 1

[directory]
read_only = ''
truncation_length = 8

[git_branch]
symbol = 'branch '

[git_commit]
tag_disabled = false
tag_symbol = ' tag '

[status]
disabled = false
format = '[with exit code $status $common_meaning$signal_name]($style) '

[character]
error_symbol = '[\$](bold red)'
success_symbol = '[\$](bold green)'
