#cloud-config
runcmd:
  # Install Ansible
  # - [ "apt", "install", "software-properties-common" ]
  - [ "apt-add-repository", "--yes", "--update", "ppa:ansible/ansible" ]
  - [ "apt", "install", "--yes" ,"--no-install-recommends", "ansible" ]
