---
- name: verify
  hosts: all
  tasks:
    - name: assert test environment
      block:
        - name: determine remote user
          command: whoami
          register: result
          changed_when: False
        - name: assert remote user
          assert:
            that:
              - result.stdout == "vagrant"
            fail_msg: "actual result is {{ result.stdout }}"
    - name: test swap size for current session
      block:
        - name: determine swap size
          command: bash -c "grep SwapTotal /proc/meminfo | awk '{print $2}'"
          register: result
          changed_when: False
        - name: assert swap size
          assert:
            that:
              - result.stdout == "0"
            fail_msg: "actual size is {{ result.stdout }}"
    - name: test swap size after rebooting
      block:
        - name: reboot machine
          become: yes
          reboot: null
        - name: determine swap size
          command: bash -c "grep SwapTotal /proc/meminfo | awk '{print $2}'"
          register: result
          changed_when: False
        - name: assert swap size
          assert:
            that:
              - result.stdout == "0"
            fail_msg: "actual size is {{ result.stdout }}"
