---
- name: Apply dependent roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  with_items:
    - dependencies/bashrc_dir

- name: Include task pyenv
  ansible.builtin.import_tasks: pyenv.yml

- name: Include task version
  ansible.builtin.import_tasks: version.yml

- name: Include task poetry
  ansible.builtin.import_tasks: poetry.yml

- name: Include task awscli
  ansible.builtin.import_tasks: awscli.yml

- name: Include task cpplint
  ansible.builtin.import_tasks: cpplint.yml
