---
- ansible.builtin.include_role:
    name: dependencies/bashrc_dir

- include_tasks: pyenv.yml
- include_tasks: version.yml
- include_tasks: poetry.yml
- include_tasks: awscli.yml
- include_tasks: cpplint.yml
