---
- name: Apply dependent roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  with_items:
    - dependencies/bashrc_dir

- name: Include task pyenv
  include_tasks: pyenv.yml

- name: Include task version
  include_tasks: version.yml

- name: Include task poetry
  include_tasks: poetry.yml

- name: Include task awscli
  include_tasks: awscli.yml

- name: Include task cpplint
  include_tasks: cpplint.yml
