---
- name: Check whether already installed uv
  ansible.builtin.command: bash -cl "type uv"
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: Install uv
  when: checked_result.rc == 1
  block:
    - name: Install requirements
      become: yes
      ansible.builtin.apt:
        name:
          - curl
    - name: Create temporary working directory
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir
    - name: Download uv-installer
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: "{{ tmpdir.path }}/uv-installer"
    - name: Execute uv-installer
      # noqa no-changed-when
      ansible.builtin.command: "bash {{ tmpdir.path }}/uv-installer"
    - name: Remove temporary working directory
      ansible.builtin.file:
        path: "{{ tmpdir.path }}"
        state: absent
