---

- name: Install requirements
  become: yes
  ansible.builtin.apt:
    name: python3-setuptools

- name: Install packages
  ansible.builtin.pip:
    name: poetry
    executable: /home/vagrant/.pyenv/shims/pip
