---
- name: Apply dependent roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  with_items:
    - dependencies/bashrc_dir
    - git

- name: Put bashrc file in ~/.bashrc.d
  ansible.builtin.copy:
    src: bashrc
    dest: ~/.bashrc.d/git-prompt.bashrc
    mode: 0755
