---
- name: Apply dependent roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  with_items:
    - dependencies/bashrc_dir
    - git

- name: Put bashrc file in ~/.bashrc.d
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc.d/git-prompt.bashrc
    mode: 0755
