---
- name: install packages
  become: yes
  ansible.builtin.apt:
    name:
      - language-pack-ja

- name: set system locale
  become: yes
  ansible.builtin.shell: localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE=ja_JP:en_US

- name: set timezone
  become: yes
  timezone:
    name: Asia/Tokyo
