---
- name: Install packages
  become: yes
  ansible.builtin.apt:
    name:
      - language-pack-ja

- name: Set system locale
  become: yes
  ansible.builtin.command: localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE=ja_JP:en_US

- name: Set timezone
  become: yes
  community.general.timezone:
    name: Asia/Tokyo
