---
- name: Check whether already installed bat
  ansible.builtin.command: bash -cl "which bat"
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: Install bat
  when: checked_result.rc == 1
  block:
    - name: Install requirements
      become: yes
      ansible.builtin.apt:
        name:
          - gcc
    - name: Install bat
      # noqa no-changed-when
      ansible.builtin.command: bash -cl "cargo install --locked bat"
