---
- name: Check whether already installed csview
  ansible.builtin.command: bash -c ". ~/.bashrc.d/rust.bashrc && which csview"
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: Install csview
  when: checked_result.rc == 1
  block:
    - name: Install requirements
      become: yes
      ansible.builtin.apt:
        name:
          - gcc
    - name: Install csview
      # noqa no-changed-when
      ansible.builtin.command: bash -c ". ~/.bashrc.d/rust.bashrc && cargo install csview"
