---

- name: check whether already installed diffr
  command: bash -c ". ~/.bashrc.d/rust.bashrc && which diffr"
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: install diffr
  when: checked_result.rc == 1
  block:
    - name: install requirements
      become: yes
      apt:
        name:
          - gcc
    - name: install diffr
      # noqa no-changed-when
      command: bash -c ". ~/.bashrc.d/rust.bashrc && cargo install diffr"
