---

- name: Check whether already installed git-graph
  ansible.builtin.command: bash -c ". ~/.bashrc.d/rust.bashrc && which git-graph"
  register: checked_result
  changed_when: False
  failed_when: checked_result.rc not in [0, 1]

- name: Install git-graph
  when: checked_result.rc == 1
  block:
    - name: Install requirements
      become: yes
      ansible.builtin.apt:
        name:
          - gcc
    - name: Install git-graph
      # noqa no-changed-when
      ansible.builtin.command: bash -c ". ~/.bashrc.d/rust.bashrc && cargo install git-graph"
