---
- name: Install packages
  become: yes
  apt:
    name:
      - fontconfig
      - fonts-inconsolata
      - fonts-noto-cjk
      - fonts-noto-color-emoji

- name: Create directory to put sddm config
  file:
    path: /home/vagrant/.config/fontconfig
    state: directory
    mode: "0755"

- name: Put fontconfig config file
  copy:
    src: fonts.conf.xml
    dest: /home/vagrant/.config/fontconfig/fonts.conf
    mode: 0644
  notify:
    - update font information caches
