FROM {{ item.image }}

RUN apt-get update \
    && apt-get install -y \
        ca-certificates \
        python \
        software-properties-common \
        sudo \
    && adduser vagrant \
    && adduser vagrant sudo \
    && echo 'Defaults exempt_group=sudo' >> /etc/sudoers
