---
- name: verify
  hosts: all
  tasks:
    - name: assert test environment
      block:
        - name: determine remote user
          ansible.builtin.command: whoami
          register: result
          changed_when: False
        - name: assert remote user
          assert:
            that:
              - result.stdout == "molecule"
            fail_msg: "actual result is {{ result.stdout }}"
    - name: test command existence
      ansible.builtin.command: bash -c "type {{ item }}"
      register: result
      changed_when: False
      with_items:
        - nkf
